# Configuration for the global limit on all currencies.
#
# Minimum Trading Amount (min-trade): set the limit on how little money are allowed to be transfer each time.
#   * Note: This value is clamped to minimum of 0.001
#   Example: setting it to 1 means Steve can only transfer to Alex at least 1 unit of currency.
#
# Min and Max are limiter for player's bank account, the limit is per-currency.
#  - enable: set to true to enforce that limit, max and min can be enabled or disabled separately.
#  - value: the minimm/maximum value that the player can have for a type of currency.
#  * Note: if min value = max value, then there is no limit.
#  Example: Setting min value to -1000 mean that Steve can take on a debt up to 1000 currency unit.
#
currency-limit:
  min-trade: 0.1
  min:
    enable: true
    value: 0.0
  max:
    enable: true
    value: 1000000000.0

# Configuration for players globally.
#
# Playtime:
#  - Tracking playtime (track-playtime): set to true to track time a player spend on the server.
#  - Detect AFK (detect-afk): set to true to detect when the player start idling and pause counting time for them.
#  - AFK threshold (afk-threshold): time since idling before we can stop counting time, in seconds.
#   * Note: the AFK detection might not be able to prevent AFK machine bypass,
#           this might be improved in the future.
#
players:
  playtime:
    track-playtime: false
    detect-afk: true
    afk-threshold: 300

# Configuration for the vault integration of AnotherCurrency.
#
# Hook Economy (hook-economy): set to true to enable disable hooking into Vault Economy API.
#   * Note: If disabled, other plugins won't be able to access ANC through Vault.
#
# Primary Currency (primary-currency): code name of the currency that will be registered with Vault.
# Leave it empty to use the first declared currency in currencies.yml
#   * Note: Due to inconsistency in reading order, it is suggested you define this if you have multiple currency.
#   * Note: This value is ignored if hook-economy is false
#
# Hook Permission (hook-permission): set to true to enable hooking into Vault Permission API.
#
vault:
  hook-economy: true
  primary-currency: ''
  hook-permission: true

# Config version number
# DO NOT change this, it is used to know what config version you are using.
config-version: 1
currencies-version: 1
